.TH User_Manager 1 "May 2024" "User Manager Manual"

.SH NAME
User_Manager \- Manage users and groups in a user manager application

.SH SYNOPSIS
.B User_Manager

.SH DESCRIPTION
.B User_Manager
is a command-line utility for managing users and groups on a system.
is a User_Manager application(program), which allows users to manage users and groups, change account information, and assign users to groups.

.SH OPTIONS
This program does not take any command-line options.

.SH COMMANDS
.TP
.B a
Manage Users.
.B
a : Add User
b : Delete User
e : Exit


.TP
.B b
Manage Groups.
.B
a : Add Group
b : Delete Group
e : Exit

.TP
.B c
Change Account Information.

.TP
.B d
Assign User to Group.

.TP
.B q
Exit The Program.

.SH USAGE
Run
.B User_Manager
in the terminal to launch the User_Manager application. Follow the on-screen instructions to perform various tasks.

.SH AUTHOR
Abdelruhman elkot <3bdo3lkot@gmail.com>

.SH REPORTING BUGS
Report bugs to <3bdo3lkot@gmail.com>